### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by KennysSparda** [boloto1979/Securiskan#1]
Hello, I would like to learn how to start the application, because following the steps in readme.md the application still does not work.
I downloaded and installed the npm dependencies with
npm i
and ran it with npm run dev
but I didn't understand how I can do the same for PHP
I think it would be of great help to include step by step instructions for running the project.
Thank you in advance for your attention!

**Comment by boloto1979** [comment]
Hello,

To get the project started using Laravel, first, use Artisan by running the following command:
```
php artisan serve
```
Next, to install the necessary dependencies, use Docker. You can build and start the containers with these commands:
```
docker-compose build
docker-compose up -d
```
Once the containers are up and running, the next step is to apply the database migrations. This can be done with the command:
```
php artisan migrate
```
If you encounter any issues related to the absence of the .env file, a simple solution is to rename the .env.example file to .env. This will create a standard copy of the configuration file that you can customize as needed.

I will update the project README with the step by step. If you face any difficulties or have any questions during the process, feel free to get in touch.

**Comment by boloto1979** [comment]
Currently, as the project is in its early stages, I am using the VirusTotal API. Therefore, please follow the steps in the Development Setup section of the README to test the application. I am developing the next updates for the project, and over time, it will not depend on third-party APIs.
